import "./globals.css";

import { Inter } from "next/font/google";

import { StoreProvider } from "@/redux/provider/StoreProvider";

import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";
import OfflineOnlineProvider from "@/components/offline-online-provider";

import AuthProvider from "@/auth/context/jwt/auth-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Flow Board",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <AuthProvider>
            <OfflineOnlineProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
              >
                <Toaster
                  position="top-right"
                  richColors // More vibrant colors
                  closeButton // Add close button
                />
                {children}
              </ThemeProvider>
            </OfflineOnlineProvider>
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
